export let words = [
  "come clean",
  "sloppy",
  "black and white",
  "ancient",
  "slack off",
  "freebie",
  "clear-cut",
  "fiddly",
  "downtime",
  "get it",
  "legit",
  "hyped",
  "attention-seeking",
  "get into",
  "cut corners",
  "big deal",
  "on the dot",
  "pricey",
  "touchy subject",
  "one-off",
  "rusty",
  "in-your-face",
  "downer",
  "packed",
  "old-school",
  "sick of",
  "white noise",
  "tricky",
  "slammed",
  "tell me about it",
  "take it easy",
  "chill",
  "on the same page",
  "give credit",
  "loaded",
  "cutting-edge",
  "chill out",
  "roughly",
  "selling point",
  "party animal",
  "wordy",
  "surefire",
  "up in the air",
  "worth a shot",
  "sharp",
  "burning desire",
  "face-time",
  "jump the gun",
  "fishy",
  "broken record",
  "schedule",
  "management",
  "leadership",
  "questionnaire",
  "statistic",
  "assessment",
  "revision",
  "outdated",
  "widespread",
  "countryside",
  "getaway",
  "cybercrime",
  "current account",
  "condominium",
  "rectangular",
  "gymnasium",
  "Anthropology",
  "commencement",
  "assessment",
  "fungus",
  "nail",
  "juggle",
  "relegate",
  "sloppy",
  "ancient",
  "freebie",
  "fiddly",
  "downtime",
  "legit",
  "hyped",
  "pricey",
  "rusty",
  "downer",
  "packed",
  "tricky",
  "slammed",
  "chill",
  "loaded",
  "roughly",
  "wordy",
  "surefire",
  "sharp",
  "fishy",
  "sharply",
  "considerably",
  "significantly",
  "substantially",
  "steadily",
  "slightly",
];
